CREATE TABLE Client(
IdClient INT PRIMARY KEY IDENTITY(1,1),
LegalName VARCHAR(200) NOT NULL,
TradeName VARCHAR(100)
);
GO

CREATE TABLE Items(
IdItem INT PRIMARY KEY IDENTITY(1,1),
description VARCHAR(200) NOT NULL
);
GO

CREATE TABLE Orders(
IdOrder INT PRIMARY KEY IDENTITY(1,1),
ClientID INT NOT NULL,
OrderDate DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE OrderItems(
IdOrderItem INT PRIMARY KEY IDENTITY(1,1),
ItemID INT NOT NULL,
OrderID INT NOT NULL,
quantity INT NOT NULL
);
GO

CREATE TABLE ProductionOrders (
IdProductionOrder INT PRIMARY KEY IDENTITY(1,1),
OrderID INT NOT NULL,
ManufacturingDeadline DATETIME NOT NULL,
ProductionOrderStatus VARCHAR(15) DEFAULT 'aberto'
);
GO

CREATE TABLE TestTrigger(
  History VARCHAR(200)
);
GO
